version: "3.9"
services:
  yubi-bridge:
    build:
      context: ./
      dockerfile: Dockerfile
    privileged: true
    volumes:
      - "/dev:/dev"
    environment: 
      - URL=${DEFGUARD_URL}
      - WORKER_ID=${WORKER_ID}
      - DEFGUARD_TOKEN=${DEFGUARD_TOKEN}
    # By default run as Defguard client
    command: --grpc

