name: Build Debian Package

on:
  pull_request:

jobs:
  build-deb-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get install -y perl build-essential debhelper python3-pytest scdaemon yubikey-manager
      - name: Build Debian package
        run: dpkg-buildpackage -us -uc
      - name: Upload Debian package artifact
        uses: actions/upload-artifact@v2
        with:
          name: deb-package
          path: ../*.deb
